services:
  - type: web
    name: lifeline-frontend
    staticPublishPath: ./dist
    buildCommand: npm run build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
